### ISSUE TITLE
Datastore Tutorial Issue

### ISSUE THREAD

**Issue by jgunnink** [GoogleCloudPlatform/getting-started-ruby#106]
Hello, it appears after #96 that the docs on the google cloud website have not been updated.

I was following the tutorial here to learn about rails and cloud datastore here: https://cloud.google.com/ruby/getting-started/using-cloud-datastore however, the docs point to directories and application structure which no longer exists. How should one go about this? Do the tutorial docs need to be updated on the google cloud site and/or has the tutorial been updated somewhere else which I should now follow?

Thanks in advance.

**Comment by TheRoyalTnetennba** [comment]
AFAICT this was updated. Thanks for reporting. Lmk if you notice anything that's still an issue.
