### ISSUE TITLE
Enabling force_ssl results in infinite redirect loop

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/getting-started-ruby#26]
Deploying a Rails app on a Managed VM with SSL enabled in the config/environments/production.rb as follows:

```
config.force_ssl = true
```

causes an infinite redirect loop. It appears that the HTTP_X_FORWARDED_PROTO HTTP header isn’t set properly.

force_ssl relies on the HTTP_X_FORWARDED_PROTO HTTP header to determine whether or not the request was an HTTPS request. If this setting isn't set to https then you end up with an infinite redirect loop as force_ssl will always think the forwarded request isn't HTTPS.

When we deploy Rails to a managed VM it appears each machine is set up with nginx in front? Is it possible for nginx to take care of the header?

Note: With force_ssl enabled I also had to disable health checks as they are sent http (not https) so Rails returned a 301 redirect. This caused the instance to be classified as unhealthy and it wouldn't receive any requests.

**Comment by bbnnt** [comment]
same here, not that cool :/
any updates on this ?

**Comment by samkelly** [comment]
Still an issue for me

**Comment by JustinBeckwith** [comment]
Greetings folks!  We know this is an issue, and we're actively working on it.  This is more of an all up App Engine thing than a Ruby thing.  We're tracking it here:

https://code.google.com/p/googleappengine/issues/detail?id=12252

**Comment by austinkettner** [comment]
Any update here? Considering this is a fairly critical component, I am a bit perplexed by the lack of any update here or in the code.google issue for months.

**Comment by samkelly** [comment]
@austinkettner my current work-around is something like this: https://gist.github.com/samkelly/fbb0c1c2d6dfe929dc74cf4617647f0e

**Comment by frankyn** [comment]
@austinkettner and @samkelly You can fix this with an update to the AppEngine environment. In your app.yaml file remove the line `vm: true` and add `env: flex`. This will have the updated environment which fixes the HTTP_X_FORWARDED_PROTO error.

**Comment by JustinBeckwith** [comment]
You can read about the side effects here:
https://cloud.google.com/appengine/docs/flexible/python/upgrading

For Ruby, it largely should 'just work'

**Comment by samkelly** [comment]
thanks!
