### ISSUE TITLE
app.yaml automatic_scaling / resources conf issues

### ISSUE THREAD

**Issue by benbonnet** [GoogleCloudPlatform/getting-started-ruby#28]
Hello;

For anyone reading this, thanks for the help in understanding how things work

I've deployed with the setup you're providing in your example in app.yaml. I keep having two running instances, showing higher resources than shat's specified in your example : `g1-small (1 vCPU, 1.7 GB memory)`

The app.yaml says the following :

```
resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10
```

So I don't understand this 1.7GB memory running,and that why instances are running at the same time

Thanks a lot for your elightment !

**Comment by dazuma** [comment]
App Engine assigns a machine type based on the amount of CPU and memory you've specified. The machine is guaranteed to have at least the level of resources you've specified, but it might have more. See https://cloud.google.com/appengine/docs/flexible/ruby/reference/app-yaml#resource-settings

App Engine also generally provisions multiple instances of your application by default. See https://cloud.google.com/appengine/docs/flexible/ruby/reference/app-yaml#services for information on how you can control the scaling.
