### ISSUE TITLE
Advise on best practices for storing database credentials

### ISSUE THREAD

**Issue by MarkBennett** [GoogleCloudPlatform/getting-started-ruby#30]
From a security perspective isn't it bad form to store the production sql user & password in the config/database.yml on a development machine as this would likely get checked into version control? It seems like Google is recommending [using the Google SQL Proxy instead when working from a App Engine Managed VM](https://cloud.google.com/sql/docs/dev-access#gaev2-csqlv2).

Would it be possible to address how to store these passwords somewhere in the getting started guide? I appreciate using SQL Proxy might be beyond the scope of this guide. If so, could you link to some best practices for doing so elsewhere? Perhaps it would be good to make clear that checking production credentials into version control isn't normally done?

Thanks!

**Comment by jeffmendoza** [comment]
config/database.yml is in the .gitignore so that it doesn't get accidentally committed.

Looks like we should mention this explicitly here: https://cloud.google.com/ruby/getting-started/using-cloud-sql#configure_settings

Thanks!

**Comment by MarkBennett** [comment]
Thanks. You guys are really awesome about the quick replies!

**Comment by frankyn** [comment]
Moved to internal tracking.
