### ISSUE TITLE
3-cloud-storage/README.md is out of date

### ISSUE THREAD

**Issue by CommanderTso** [GoogleCloudPlatform/getting-started-ruby#34]
I'm working through putting together the cloud storage project, and I've found a couple spots that are incorrect in the Readme version:

`Open config/application.rb, edit the below line to replace bucket with the name of your bucket:`

This implies that the config line is already in there, which it isn't.  It'd be good to either put it in there. I stuck it into the Module section of the file, which seems to work.

The readme also mentions `fog_credentials.example.yml`, but that doesn't exist.  Does that refer to `settings.yml`?

As a note, when I went back and did the instructions from https://cloud.google.com/ruby/getting-started/using-cloud-storage, things went great.

**Comment by jeffmendoza** [comment]
Thanks for noticing! I updated the title to be a bit more specific. Yes, as you found https://cloud.google.com/ruby/getting-started/using-cloud-storage is up to date.

**Comment by frankyn** [comment]
Moved to internal tracking list.
