### ISSUE TITLE
6-task-queueing with datastore: NoMethodError: undefined method `find_by_id' for Book:Class

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/getting-started-ruby#39]
I receive the following error when the workers run (using `backend:datastore` for `6-task-queueing`. 

```
13:26:49 worker.2       | Book lookup request (5679413765079040)
13:26:49 worker.2       | rake aborted!
13:26:49 worker.2       | NoMethodError: undefined method `find_by_id' for Book:Class
13:26:49 worker.2       | 6-task-queueing/lib/active_job/queue_adapters/pub_sub_queue_adapter.rb:40:in `block in run_worker!'
13:26:49 worker.2       | 6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:376:in `block (2 levels) in listen'
13:26:49 worker.2       | 6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:376:in `each'
13:26:49 worker.2       | 6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:376:in `block in listen'
13:26:49 worker.2       | 6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:373:in `loop'
13:26:49 worker.2       | 6-task-queueing/vendor/bundle/ruby/2.2.0/gems/gcloud-0.4.0/lib/gcloud/pubsub/subscription.rb:373:in `listen'
13:26:49 worker.2       | 6-task-queueing/lib/active_job/queue_adapters/pub_sub_queue_adapter.rb:36:in `run_worker!'
13:26:49 worker.2       | 6-task-queueing/lib/tasks/run_worker.rake:4:in `block in <top (required)>'
```

This is fixed by editing `lib/active_job/queue_adapters/pub_sub_queue_adapter.rb` and changing `find_by_id` to `find`

**Comment by jeffmendoza** [comment]
@thagomizer if you're interested

**Comment by thagomizer** [comment]
`find` will throw an exception if the record isn't there. `find_by_id` just returns `nil`. The proposed patch will work in most cases but will crash hard if the book is missing. 

`find_by_id` is a dynamic finder and shouldn't be causing a `NoMethodError` if the id column is present in the database and the database interface layer is working correctly.

**Comment by bshaffer** [comment]
Yeah, I found out it's because the `book.rb` model for `datastore` does [not actually extend ActiveRecord](https://github.com/GoogleCloudPlatform/getting-started-ruby/blob/master/6-task-queueing/structured_data/datastore/app/models/book.rb), hence the method not found error. The solution will probably be to just add `find_by_id` to the datastore model.
