### ISSUE TITLE
Bookshelf App Crashes

### ISSUE THREAD

**Issue by bparanj** [GoogleCloudPlatform/getting-started-ruby#4]
The bookshelf app: https://library-1071.appspot.com gives the following error:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

How do I check the logs? How to fix this problem?

**Comment by remi** [comment]
The bookshelf app logs should appear in the [Logs Viewer][] for your project in the Developers Console (*under __Monitoring > Logs__*).

See [Viewing logs][] for a screenshot and details.

When running in production, the app writes logs to [`/var/log/app_engine/custom_logs`][], which is monitored for logs in [App Engine Managed VM applications][].  Output written to STDOUT, STDERR, and syslog will also appear in the Logs Viewer.

[Viewing logs]: https://cloud.google.com/ruby/getting-started/logging-application-events#viewing_logs
[Logs Viewer]: https://console.developers.google.com/project/_/logs
[`/var/log/app_engine/custom_logs`]: https://github.com/GoogleCloudPlatform/getting-started-ruby/blob/64271e66c4a290771ac3149737a4ab20cef00f73/config/environments/production.rb#L56
[App Engine Managed VM applications]: https://cloud.google.com/appengine/docs/managed-vms/custom-runtimes#logging

**Comment by remi** [comment]
Which branch of the project did you deploy?  Does the application run locally for you?  You can also try running the application locally in production mode by running, which may reproduce your issues:

```sh
$ rails server --environment=production
```

If you are running any step past 1-hello-world, be sure to check that your **`production:`** environment settings are configured in `config/database.yml` and/or `config/settings.yml`.

**Comment by bparanj** [comment]
I have decided to use Puppet to deploy code. I don't need GAE.
