### ISSUE TITLE
Update sample and bookshelf tutorial docs with gem "google-cloud-ruby"

### ISSUE THREAD

**Issue by dhirajbajaj** [GoogleCloudPlatform/getting-started-ruby#61]
Hello Guys, 

As referenced in this thread https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/910

The bookshelf tutorial isn't going smoothly and got stucking issues due to no mention on setting up credentials, env variables, service accounts, confusion about naming convention, deployment troubleshooting in the tutorial or code-sample etc. 

Hope you find the pointers useful for better docs/sample.

**Comment by olilogic77** [comment]
Thanks - you seem to have resolved the issue that I got with the gcloud/google-cloud rename.  It also looks like the books.rb file needs a bit more work done to reference the new gem format and include the authentication call to the .json key file - am I on the right track (sorry, still a noob rubyist)?

**Comment by dhirajbajaj** [comment]
@olilogic77 You can refer to https://github.com/Agrimatics/active-model-cloud-datastore repo which uses google-cloud-datastore gem with emulator for local dev.
