### ISSUE TITLE
Move this sample into ruby-docs-samples

### ISSUE THREAD

**Issue by beccca** [GoogleCloudPlatform/getting-started-ruby#63]
To reduce maintenance and not have to duplicate issues / etc across all Ruby samples that are used in or referenced by our [cloud.google.com](https://cloud.google.com/) documentation, this sample application should be moved into [ruby-docs-samples](https://github.com/GoogleCloudPlatform/ruby-docs-samples)

See tracking issue in ruby-docs-samples repo: [...](#)

Many of the issues we file are for things such as "update all Ruby samples to use the latest X.Y.Z version of the ABC library."  This type of maintenance is more difficult with our samples in 2 repositories.  It's easy to forget about this repository ... plus you have to `git grep` across both.  Yuck!

We also will be making it simpler to run end-to-end tests for all samples found in ruby-docs-samples and having these Rails applications as part of that test pipeline will simplify things greatly!

Before this can be closed and the repo completely moved ...
- [ ] Ensure that all documentation is updated to use the Bookshelf sample found in ruby-docs-samples
- [ ] Ensure that all interactive tutorials are updated to use the Bookshelf sample found in ruby-docs-samples

**Comment by dazuma** [comment]
Moved to buganizer (id 109937659). Closing.
