### ISSUE TITLE
OAuth URLs are not valid during beta of Flexible App Engine 

### ISSUE THREAD

**Issue by warmfusion** [GoogleCloudPlatform/getting-started-ruby#71]
Page: https://cloud.google.com/ruby/getting-started/authenticate-users

Problem: Creating new credentials for use with oauth ID indicates a set of URL's which should be used which are based on the {{Project Name}}.appspot.com.

This is not valid as according to [the App Engine Flexible Release](https://cloud.google.com/appengine/docs/flexible/ruby/upgrading) documentation;

> Domain update
> 
> Traffic is now served from the appspot-preview.com domain instead of the appspot.com domain. All traffic from the App Engine flexible environment will be automatically redirected to the new domain. All App Engine Standard traffic will continue to be through appspot.com. When the App Engine flexible environment is generally available (GA), users will be able to use the appspot.com or appspot-preview.com domains for routing traffic.

The URLs that are generated are based on the version and project name, which is not necessarily known beforehand preventing the oauth-credentials callback whitelist to be effectivly populated.

A workaround may be possible, but I do not know GCP well enough to speculate.

**Comment by remi** [comment]
Thanks Toby!

When you visit your beta application at https://project.appspot.com then you are redirected to https://version-dot-project.appspot-preview.com

Instead, visit your application directly at https://project.appspot-preview.com.  This does not redirect to a URL containing the version number

The redirection from appspot.com to appspot-preview.com can be helpful but, as you pointed out, it is currently not ideal and will not work for OAuth 2 redirect URIs.

I reproduced the issue you are running into and ended up with an angry **Error: redirect_uri_mismatch** message.  I also confirmed that it works if you use appspot-preview.com for your redirect URI when defining your OAuth client ID and then visit the application at https://project.appspot-preview.com.  Login works great 😄 

I'll update the page to use appspot-preview.com

Thanks so much for finding and reporting this!

**Comment by warmfusion** [comment]
Hey thanks for the detailed response!

I've added the whitelist entries using the appspot-preview.com url and it's working perfectly.

Something to watch out for as all the links to the apps in the console get bounced to the preview while the beta is in operation, but its not the end of the world now I know the alternative url as a workaround.

**Comment by remi** [comment]
Glad you got it working!

Updated the page to include appspot-preview.com when creating OAuth clients
https://cloud.google.com/ruby/getting-started/authenticate-users

Including appspot.com and appspot-preview.com during the beta to cover all bases during the beta!

Thanks so much for the report
