### ISSUE TITLE
New lookup job errors if it cant find a book

### ISSUE THREAD

**Issue by jeffmendoza** [GoogleCloudPlatform/getting-started-ruby#72]
reproduce by creating a book with a gibberish name, I get:

Exception
TypeError

Error
no implicit conversion of NoMethodError into String

/home/jeffmendoza/git/getting-started-ruby/7-compute-engine/app/jobs/lookup_book_details_job.rb:31:in `+'
/home/jeffmendoza/git/getting-started-ruby/7-compute-engine/app/jobs/lookup_book_details_job.rb:31:in `block in perform'
/home/jeffmendoza/.gem/gems/google-api-client-0.9.20/lib/google/apis/core/http_command.rb:116:in `rescue in execute'
/home/jeffmendoza/.gem/gems/google-api-client-0.9.20/lib/google/apis/core/http_command.rb:95:in `execute'
/home/jeffmendoza/.gem/gems/google-api-client-0.9.20/lib/google/apis/core/base_service.rb:351:in `execute_or_queue_command'
/home/jeffmendoza/.gem/gems/google-api-client-0.9.20/generated/google/apis/books_v1/service.rb:2043:in `list_volumes'
/home/jeffmendoza/git/getting-started-ruby/7-compute-engine/app/jobs/lookup_book_details_job.rb:29:in `perform'
...

**Comment by frankyn** [comment]
Acknowledged, looking into it now.
