### ISSUE TITLE
Update Cloud SDK installation instruction in main README

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/getting-started-ruby#76]
**Issue:**

The root README contains information to get started and includes installation instructions for Cloud SDK. The instructions are presented with a link and a command. As a passing developer, I wouldn't try the link and just run the command presented right after. It also doesn't include `gcloud init` to setup the default project.

**Possible-Changes:**

I vote to remove the shell command and just link the user out.

**Comment by dazuma** [comment]
Moved to buganizer internally. Closing.
